.ONESHELL:
SHELL := /bin/bash
all: help

############################################################################
# PROJECT CONFIG
PROJECT_NAME := example-proj
CONTAINER_NAME := backend
IMAGE_REGISTRY := localhost:5000
IMAGE_NAME := $(PROJECT_NAME)/$(CONTAINER_NAME)
RELEASE_DATE := $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
RELEASE_DATE_TAG := $(shell date -u +'%Y-%m-%dT%H-%M-%SZ')

############################################################################
# APP
clean: ## clean the app
	rm -rf build

############################################################################
# DOCKER
docker: docker-build docker-push ## build and push the docker image, extra args with DOCKER_ARGS=... (e.g. --no-cache)

docker-push: ## push the docker container
	docker image push $(IMAGE_REGISTRY)/$(IMAGE_NAME):latest \
		&& docker image push $(IMAGE_REGISTRY)/$(IMAGE_NAME):$(RELEASE_DATE_TAG)

docker-build: ## build the docker image, extra args with DOCKER_ARGS=... (e.g. --no-cache)
	eval $(ssh-agent) && ssh-add ~/.ssh/id_ed25519
	DOCKER_BUILDKIT=1 docker buildx build \
		$${DOCKER_ARGS} \
		--ssh default \
		--network host \
		--build-arg BUILD_DATE=$(RELEASE_DATE) \
		--build-arg VCS_REF=$(RELEASE_VERSION) \
		-t $(IMAGE_NAME):$(RELEASE_DATE_TAG) \
		-t $(IMAGE_NAME):latest \
		-t $(IMAGE_REGISTRY)/$(IMAGE_NAME):$(RELEASE_DATE_TAG) \
		-t $(IMAGE_REGISTRY)/$(IMAGE_NAME):latest \
		.

############################################################################
# HELP
help: ## print this help
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}'
